rocker --network host --privileged --nvidia --x11 --user --name autoware \
  	--env="USER" \
	--env="RMW_IMPLEMENTATION=rmw_cyclonedds_cpp" \
	--env="ROS_DOMAIN_ID=0" \
	--env="ROS_LOCALHOST_ONLY=0" \
	--env="VEHICLE_ID=default" \
	--volume /dev \
	--volume $HOME/autoware:$HOME/autoware \
	--volume $HOME/autoware_map:$HOME/autoware_map \
	--volume $HOME/AWSIM_v1.1.0_F1TENTH:$HOME/AWSIM_v1.1.0_F1TENTH \
	-- ghcr.io/autowarefoundation/autoware-universe:humble-latest-cuda-amd64
